export const CONTENT = {
  en: {
    meta: {
      title: "VerticalClap — The Studio for Addictive Vertical Dramas",
      description: "Generate vertical micro-dramas with bible, scripts and cliffhangers — ready to shoot in under 30 seconds.",
    },
    nav: {
      login: "Sign in",
      cta: "Create my series →",
    },
    hero: {
      badge: "Micro-Drama Studio · AI · 9:16",
      h1_1: "Stories",
      h1_2: "impossible to",
      h1_3: "scroll past.",
      sub: "Generate vertical micro-dramas with bible, scripts and cliffhangers — ready to shoot in under 30 seconds.",
      cta1: "See an example →",
      cta2: "Create my series",
      disclaimer: "€9/month · No commitment · Cancel anytime",
    },
    demo: {
      badge: "How it works",
      h2_1: "One idea.",
      h2_2: "A complete series.",
      input_label: "Your idea",
      input_text: '"A girl finds out her boyfriend is engaged to her mother."',
      tags: ["Vertical Drama", "10 episodes", "90 sec"],
      arrow_label: "28s",
      output_label: "Your series",
      output_title: "The Rival Mother",
      output_logline: "« She loved her mom. She loved her man. Both just merged into one. »",
      output_items: [
        "✓  Full bible — 2 characters, central tension",
        "✓  10 sequenced episodes + cliffhangers",
        "✓  9:16 vertical scripts ready to shoot",
        "✓  Teleprompter mode included",
      ],
      cta: "Generate my first series →",
    },
    market: {
      badge: "Why now",
      h2_1: "Vertical drama is",
      h2_2: "the next wave.",
      stats: [
        { stat: "500M+", label: "ReelShort downloads in 2 years", icon: "📱" },
        { stat: "94%", label: "average watch time on micro-dramas", icon: "👁" },
        { stat: "3×", label: "more engagement than long-form content", icon: "⚡" },
        { stat: "2026", label: "projected European market explosion", icon: "🌍" },
      ],
      quote: '"DramaBox and ReelShort each generate $100M+/year. The global vertical studio for creators doesn\'t exist yet. VerticalClap is building it."',
    },
    pipeline: {
      badge: "The pipeline",
      h2_1: "From concept to shoot.",
      h2_2: "Fully automated.",
      steps: [
        { step: "01", icon: "🎲", title: "The Mixer", desc: "Cast, universe, central secret. 8 themed packs in one click. You set the frame — AI creates.", color: "#E85C3A" },
        { step: "02", icon: "📖", title: "Series Bible", desc: "Characters, tensions, logline, full scene breakdown. From vague idea to structure in 10 seconds.", color: "#4a8a5a" },
        { step: "03", icon: "🎬", title: "9:16 Scripts", desc: "Each episode: a killer hook, sharp dialogue, vertical framing notes. Ready to shoot.", color: "#E85C3A" },
        { step: "04", icon: "🎲", title: "3 Variations", desc: "Intense, subtle, fast — 3 versions of every script, generated in parallel. Pick the best.", color: "#4a8a5a" },
        { step: "05", icon: "📱", title: "Shoot Mode", desc: "Auto-scroll teleprompter, adjustable size and speed. Put your phone down. Action.", color: "#E85C3A" },
      ],
    },
    social: {
      badge: "Creator results",
      h2_1: "Series made with VerticalClap",
      h2_2: "perform.",
      disclaimer: "Beta creator data. Results vary by audience and niche.",
      results: [
        { handle: "@leo_fiction", serie: "Dark Inheritance", stat: "2.1k comments", ep: "Ep. 1 — 94% watch time", emoji: "🔥" },
        { handle: "@drama_mobile", serie: "The Contract", stat: "38k views in 48h", ep: "Ep. 3 — shared 800 times", emoji: "⚡" },
        { handle: "@scrolldrama_en", serie: "Double Life", stat: "4.7k saves", ep: "Ep. 2 — 89% retention", emoji: "🎬" },
      ],
    },
    authors: {
      h2: "Built by storytellers\nand filmmakers.",
      p1: "VerticalClap wasn't built by developers who read threads about micro-drama. It was built by people who understand narrative structure, mise en scène, and the addiction mechanics of vertical storytelling.",
      p2: "Every prompt, every script structure, every cliffhanger — engineered to perform on TikTok, Reels and Shorts.",
    },
    pricing: {
      badge: "Pricing",
      h2: "Create my series",
      sub: "Cancel anytime · No commitment",
      placeholder: "your@email.com",
      plans: [
        {
          name: "Creator",
          price: "€9",
          period: "/month",
          items: ["⚡ Vertical Drama · micro-drama", "Up to 20 episodes", "1 to 2 min scripts", "Shoot Mode + Teleprompter", "PDF Export", "Unlimited saves"],
          cta: "Get started →",
          highlighted: false,
        },
        {
          name: "Pro",
          price: "€19",
          period: "/month",
          badge: "⭐ RECOMMENDED",
          items: ["⚡ Vertical + 🎭 Premium Series", "Up to 90 episodes", "Short & long format scripts", "Shoot Mode + Teleprompter", "🎲 3 script variations", "🔥 Viral title generator", "PDF Export", "Unlimited saves"],
          cta: "Start Pro →",
          highlighted: true,
        },
      ],
      secure: "Secured by Stripe",
    },
    footer: {
      copy: "© 2026 VerticalClap",
      links: [
        { label: "Contact", href: "mailto:verticalclapapp@gmail.com" },
        { label: "Examples", href: "/exemples" },
        { label: "Terms", href: "/cgu" },
        { label: "Privacy", href: "/confidentialite" },
      ],
    },
  },
  fr: {
    meta: {
      title: "VerticalClap — Le studio IA des micro-dramas addictifs",
      description: "Génère des micro-dramas verticaux avec bible, scripts et cliffhangers — prêts à tourner en moins de 30 secondes.",
    },
    nav: {
      login: "Se connecter",
      cta: "Créer ma série →",
    },
    hero: {
      badge: "Studio Micro-Drama · IA · 9:16",
      h1_1: "Des séries",
      h1_2: "impossibles à",
      h1_3: "scroller.",
      sub: "Génère des micro-dramas verticaux avec bible, scripts et cliffhangers — prêts à tourner en moins de 30 secondes.",
      cta1: "Voir un exemple →",
      cta2: "Créer ma série",
      disclaimer: "9€/mois · Sans engagement · Annulable à tout moment",
    },
    demo: {
      badge: "Comment ça marche",
      h2_1: "Une idée.",
      h2_2: "Une série complète.",
      input_label: "Ton idée",
      input_text: '"Une fille découvre que son petit ami est fiancé à sa mère."',
      tags: ["Vertical Drama", "10 épisodes", "1 min 30"],
      arrow_label: "28s",
      output_label: "Ta série",
      output_title: "Mère Rivale",
      output_logline: "« Elle aimait sa mère. Elle aimait son homme. Les deux venaient de fusionner. »",
      output_items: [
        "✓  Bible complète — 2 personnages, tension centrale",
        "✓  10 épisodes séquencés + cliffhangers",
        "✓  Scripts prêts à tourner — format 9:16",
        "✓  Mode Tournage + Téléprompteur",
      ],
      cta: "Générer ma première série →",
    },
    market: {
      badge: "Pourquoi maintenant",
      h2_1: "Les micro-dramas sont",
      h2_2: "la prochaine vague.",
      stats: [
        { stat: "500M+", label: "téléchargements de ReelShort en 2 ans", icon: "📱" },
        { stat: "94%", label: "de watch time jusqu'à la fin sur les micro-dramas", icon: "👁" },
        { stat: "3×", label: "plus d'engagement qu'un format long", icon: "⚡" },
        { stat: "2026", label: "explosion du marché européen estimée", icon: "🌍" },
      ],
      quote: '"DramaBox et ReelShort génèrent chacun plus de 100M$/an. Le studio vertical mondial des créateurs n\'existe pas encore. VerticalClap est en train de le construire."',
    },
    pipeline: {
      badge: "Le pipeline",
      h2_1: "Du concept au tournage.",
      h2_2: "Tout. Automatiquement.",
      steps: [
        { step: "01", icon: "🎲", title: "Le Mixeur", desc: "Casting, univers, secret central. 8 packs thématiques en 1 clic. Tu cadres — l'IA crée.", color: "#E85C3A" },
        { step: "02", icon: "📖", title: "La Bible Express", desc: "Personnages, tensions, logline, séquencier complet. De l'idée floue à la structure en 10 secondes.", color: "#4a8a5a" },
        { step: "03", icon: "🎬", title: "Scripts 9:16", desc: "Chaque épisode : hook choc, dialogues millimétrés, directives de cadrage vertical. Prêt à tourner.", color: "#E85C3A" },
        { step: "04", icon: "🎲", title: "3 Variations", desc: "Intense, subtil, rapide — 3 versions de chaque script générées en parallèle. Tu choisis la meilleure.", color: "#4a8a5a" },
        { step: "05", icon: "📱", title: "Mode Tournage", desc: "Téléprompteur auto-scroll, taille et vitesse réglables. Pose ton téléphone. Tu tournes.", color: "#E85C3A" },
      ],
    },
    social: {
      badge: "Résultats des créateurs",
      h2_1: "Les séries créées avec VerticalClap",
      h2_2: "performent.",
      disclaimer: "Données issues de créateurs bêta. Résultats variables selon audience et niche.",
      results: [
        { handle: "@leo_fiction", serie: "Héritage Maudit", stat: "2.1k commentaires", ep: "Ép. 1 — 94% de watch time", emoji: "🔥" },
        { handle: "@drama_mobile", serie: "Le Contrat", stat: "38k vues en 48h", ep: "Ép. 3 — partagé 800 fois", emoji: "⚡" },
        { handle: "@seriemobile_fr", serie: "Double Vie", stat: "4.7k sauvegardes", ep: "Ép. 2 — 89% de rétention", emoji: "🎬" },
      ],
    },
    authors: {
      h2: "Conçu par des auteurs\net réalisateurs.",
      p1: "VerticalClap n'a pas été construit par des développeurs qui lisent des threads sur le micro-drama. Il a été construit par des gens qui connaissent la narration, la mise en scène et les mécaniques d'addiction du format vertical.",
      p2: "Chaque prompt, chaque structure de script, chaque cliffhanger — pensé pour performer sur TikTok, Reels et Shorts.",
    },
    pricing: {
      badge: "Tarifs",
      h2: "Créer ma série",
      sub: "Annulable à tout moment · Sans engagement",
      placeholder: "ton@email.com",
      plans: [
        {
          name: "Creator",
          price: "9€",
          period: "/mois",
          items: ["⚡ Vertical Drama · micro-drama", "20 épisodes max", "Scripts 1min – 2min", "Mode Tournage + Téléprompteur", "Export PDF", "Sauvegardes illimitées"],
          cta: "Commencer →",
          highlighted: false,
        },
        {
          name: "Pro",
          price: "19€",
          period: "/mois",
          badge: "⭐ RECOMMANDÉ",
          items: ["⚡ Vertical + 🎭 Série Premium", "Jusqu'à 90 épisodes", "Scripts courts et longs formats", "Mode Tournage + Téléprompteur", "🎲 3 variations par script", "🔥 Titres viraux IA", "Export PDF", "Sauvegardes illimitées"],
          cta: "Commencer Pro →",
          highlighted: true,
        },
      ],
      secure: "Paiement sécurisé via Stripe",
    },
    footer: {
      copy: "© 2026 VerticalClap",
      links: [
        { label: "Contact", href: "mailto:verticalclapapp@gmail.com" },
        { label: "Exemples", href: "/exemples" },
        { label: "CGU", href: "/cgu" },
        { label: "Confidentialité", href: "/confidentialite" },
      ],
    },
  },
};
